# --- SMART DATABASE CONFIGURATION ---
# If 'DB_URL' exists (Cloud), use it. Otherwise, use H2 (Local).
spring.datasource.url=${DB_URL:jdbc:h2:mem:gradecalc_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

# Let Spring Boot auto-detect driver + dialect based on URL and classpath.

# --- Hibernate Settings ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME:gradecalc.noreply@gmail.com}
spring.mail.password=${MAIL_PASSWORD:mdnqyppeevrslrsx}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
